.\" Macros
.ds PX \s-1POSIX\s+1
.de EXAMPLE .\" Format de los ejemplos
.RS 10
.BR "\\$1"
.RE
..

.TH client 0.0.0 "Junio de 2022"
.LO
.SH NAME
client \-  Aplicación cliente para coolProtocol según superCoolProtocol

.SHSINOPSIS
.HP 10
.B  client [-L \fIserverAddress\fR] [\fI -4 | -6\fR] [-P portNumber]

.SH OPCIONES

.IP "\fB-h\fR"
Imprime la ayuda y termina.

.IP "\fB\-4\fB"
Indica que se debe usar ipv4.

.IP "\fB\-6\fB"
Indica que se debe usar ipv6.


.IP "\fB\-L\fB \fIserver_address\fR"
Indica la dirección según la versión ip indicada a la cuál se conectará.

.IP "\fB\-P\fB \flserver-port\fR"
Puerto al cuál se intentará conectar. Por defecto el valor es \fI8080\fR.











